// VPMC WebApp bindings
// This file is auto-generated by Wails. Do not edit manually.

export interface Status {
	WinKey: boolean;
	Pear: boolean;
}

export interface SongInfo {
	title: string;
	artist: string;
	isPaused: boolean;
}

const { invoke } = window.runtime;

export function Play(): Promise<void> {
	return invoke('app.Play');
}

export function Pause(): Promise<void> {
	return invoke('app.Pause');
}

export function Toggle(): Promise<void> {
	return invoke('app.Toggle');
}

export function GetStatus(): Promise<Status> {
	return invoke('app.GetStatus');
}

export function GetSongInfo(): Promise<SongInfo | null> {
	return invoke('app.GetSongInfo');
}

export function GetStateInfo(): Promise<Record<string, unknown>> {
	return invoke('app.GetStateInfo');
}

export function GetConfig(): Promise<unknown> {
	return invoke('app.GetConfig');
}

export function SetMode(mode: string): Promise<void> {
	return invoke('app.SetMode', { mode });
}

export function SetPearPort(port: number): Promise<void> {
	return invoke('app.SetPearPort', { port });
}

export function Start(): Promise<void> {
	return invoke('app.Start');
}

export function Stop(): Promise<void> {
	return invoke('app.Stop');
}

export function GetDiscordConfig(): Promise<unknown> {
	return invoke('app.GetDiscordConfig');
}

export function SaveDiscordConfig(enabled: boolean, appID: string, riotID: string, btnLabel: string, btnURL: string): Promise<void> {
	return invoke('app.SaveDiscordConfig', { enabled, appID, riotID, btnLabel, btnURL });
}

export function GetMonitorConfig(): Promise<unknown> {
	return invoke('app.GetMonitorConfig');
}

export function SaveMonitorConfig(intervalMs: number, hysteresis: number, watchdogSec: number, modeThreshold: number): Promise<void> {
	return invoke('app.SaveMonitorConfig', { intervalMs, hysteresis, watchdogSec, modeThreshold });
}

export function GetStates(): Promise<unknown> {
	return invoke('app.GetStates');
}

export function GetModes(): Promise<unknown> {
	return invoke('app.GetModes');
}