// This file is auto-generated by Wails. Do not edit manually.

// Runtime provides access to wails runtime functions
export const runtime = {
	invoke: (callback: string, args?: unknown[]): Promise<unknown> => {
		return (window as any).wails.invoke(callback, args);
	},
	events: {
		on: (event: string, callback: Function): void => {
			(window as any).wails.events.on(event, callback);
		},
		off: (event: string): void => {
			(window as any).wails.events.off(event);
		},
	},
};
