// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DeleteRegion(arg1) {
  return window['go']['main']['App']['DeleteRegion'](arg1);
}

export function GetConfig() {
  return window['go']['main']['App']['GetConfig']();
}

export function GetDiscordConfig() {
  return window['go']['main']['App']['GetDiscordConfig']();
}

export function GetMonitorConfig() {
  return window['go']['main']['App']['GetMonitorConfig']();
}

export function GetRegions() {
  return window['go']['main']['App']['GetRegions']();
}

export function GetSongInfo() {
  return window['go']['main']['App']['GetSongInfo']();
}

export function GetStateInfo() {
  return window['go']['main']['App']['GetStateInfo']();
}

export function GetStates() {
  return window['go']['main']['App']['GetStates']();
}

export function GetStatus() {
  return window['go']['main']['App']['GetStatus']();
}

export function Pause() {
  return window['go']['main']['App']['Pause']();
}

export function Play() {
  return window['go']['main']['App']['Play']();
}

export function RecorderFramesMeta() {
  return window['go']['main']['App']['RecorderFramesMeta']();
}

export function RecorderLastFrameImage() {
  return window['go']['main']['App']['RecorderLastFrameImage']();
}

export function RecorderStart() {
  return window['go']['main']['App']['RecorderStart']();
}

export function RecorderStatus() {
  return window['go']['main']['App']['RecorderStatus']();
}

export function RecorderStop() {
  return window['go']['main']['App']['RecorderStop']();
}

export function SaveDiscordConfig(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['SaveDiscordConfig'](arg1, arg2, arg3, arg4, arg5);
}

export function SaveMonitorConfig(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['SaveMonitorConfig'](arg1, arg2, arg3, arg4);
}

export function SaveRegions(arg1) {
  return window['go']['main']['App']['SaveRegions'](arg1);
}

export function SetMode(arg1) {
  return window['go']['main']['App']['SetMode'](arg1);
}

export function SetPearPort(arg1) {
  return window['go']['main']['App']['SetPearPort'](arg1);
}

export function Start() {
  return window['go']['main']['App']['Start']();
}

export function Stop() {
  return window['go']['main']['App']['Stop']();
}

export function Toggle() {
  return window['go']['main']['App']['Toggle']();
}
